name: test_docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      env:
#        Docker_Hub_Username: fahad001
#        Docker_Hub_Password: Ismpetro@123
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        repository: test/vampi_docker:latest
        tags: latest, ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Vampi Docker image
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        docker build . --file Dockerfile --tag test/vampi_docker:latest
#        docker build . --file Dockerfile --tag vampi_docker:latest
        
    - name: List images
      run: docker images  
      
    - name: Docker Push
#      run: docker tag vampi_docker:latest ${{secrets.DOCKER_USER}}/vampi_docker:latest      
      run: docker push test/vampi_docker:latest
